# This is a basic workflow to help you get started with Actions

name: maven-package-deploy-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test/gh-actions-maven-release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.MAVEN_RELEASE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: checkout
        uses: actions/checkout@v2
      - name: set up maven central repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'ossrh'
          server-username: ${{ secrets.SONATYPE_ACCOUNT }}
          server-password: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Build
        run: mvn -B package -Dgpg.passphrase=${{ secrets.MAVEN_RELEASE_KEY_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_NEXUS_SECRET }}
      - name: deploy package
        run: mvn -X --batch-mode deploy -Dgpg.passphrase=${{ secrets.MAVEN_RELEASE_KEY_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_NEXUS_SECRET }}
