# This is a basic workflow to help you get started with Actions

name: CI-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ simpler-actions-example ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: checkout
        uses: actions/checkout@v2
      - name: build & test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"
      - name: Release
        uses: qcastel/github-actions-maven-cmd@master
        with:
          git-release-bot-name: "team products"
          git-release-bot-email: "products@wgtwo.com"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.GPG_SECRET_KEY }}
          ssh-passphrase: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
      - name: set up maven central repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'ossrh'
          server-username: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          server-password: ${{ secrets.SONATYPE_NEXUS_SECRET }}
      - name: Build
        run: ./mvnw -X --batch-mode package --file pom.xml compile -Dgpg.passphrase=${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_NEXUS_SECRET }}
      - name: deploy package
        run: ./mvnw -X --batch-mode deploy -Dgpg.passphrase=${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_NEXUS_SECRET }}
