name: maven-release

on:
  push:
    branches: [ test/gh-actions-maven-release ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build and test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"
